# Form implementation generated from reading ui file 'authorization.ui'
#
# Created by: PyQt6 UI code generator 6.3.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_WindowAuthorization(object):
    def setupUi(self, WindowAuthorization):
        WindowAuthorization.setObjectName("WindowAuthorization")
        WindowAuthorization.resize(1280, 720)
        WindowAuthorization.setMinimumSize(QtCore.QSize(1280, 720))
        WindowAuthorization.setMaximumSize(QtCore.QSize(1280, 720))
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(14)
        WindowAuthorization.setFont(font)
        WindowAuthorization.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.ArrowCursor))
        WindowAuthorization.setMouseTracking(False)
        WindowAuthorization.setTabletTracking(False)
        WindowAuthorization.setStyleSheet("background: #fff")
        self.centralwidget = QtWidgets.QWidget(WindowAuthorization)
        self.centralwidget.setObjectName("centralwidget")
        self.btn_login = QtWidgets.QPushButton(self.centralwidget)
        self.btn_login.setGeometry(QtCore.QRect(820, 370, 351, 71))
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(22)
        font.setBold(False)
        font.setWeight(50)
        self.btn_login.setFont(font)
        self.btn_login.setFocusPolicy(QtCore.Qt.FocusPolicy.StrongFocus)
        self.btn_login.setStyleSheet("QPushButton {\n"
"background-color: rgb(228, 107, 134);\n"
"border: none;\n"
"border-radius: 10px}\n"
"\n"
"QPushButton:hover {\n"
"border: 1px solid  rgb(0, 0, 0);\n"
"background-color: rgba(228, 107, 134, 0.9)\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"border:3px solid  rgb(0, 0, 0);\n"
"background-color: rgba(228, 107, 134, 1)\n"
"}")
        self.btn_login.setCheckable(False)
        self.btn_login.setObjectName("btn_login")
        self.line_login = QtWidgets.QLineEdit(self.centralwidget)
        self.line_login.setGeometry(QtCore.QRect(820, 190, 351, 51))
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(14)
        self.line_login.setFont(font)
        self.line_login.setTabletTracking(False)
        self.line_login.setFocusPolicy(QtCore.Qt.FocusPolicy.StrongFocus)
        self.line_login.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.DefaultContextMenu)
        self.line_login.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.line_login.setInputMethodHints(QtCore.Qt.InputMethodHint.ImhNone)
        self.line_login.setMaxLength(24)
        self.line_login.setEchoMode(QtWidgets.QLineEdit.EchoMode.Normal)
        self.line_login.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.line_login.setCursorMoveStyle(QtCore.Qt.CursorMoveStyle.LogicalMoveStyle)
        self.line_login.setClearButtonEnabled(False)
        self.line_login.setObjectName("line_login")
        self.label_autor_text = QtWidgets.QLabel(self.centralwidget)
        self.label_autor_text.setGeometry(QtCore.QRect(820, 610, 361, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.label_autor_text.setFont(font)
        self.label_autor_text.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_autor_text.setObjectName("label_autor_text")
        self.line_password = QtWidgets.QLineEdit(self.centralwidget)
        self.line_password.setGeometry(QtCore.QRect(820, 270, 351, 51))
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(14)
        self.line_password.setFont(font)
        self.line_password.setTabletTracking(False)
        self.line_password.setFocusPolicy(QtCore.Qt.FocusPolicy.StrongFocus)
        self.line_password.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.DefaultContextMenu)
        self.line_password.setInputMethodHints(QtCore.Qt.InputMethodHint.ImhHiddenText|QtCore.Qt.InputMethodHint.ImhNoAutoUppercase|QtCore.Qt.InputMethodHint.ImhNoPredictiveText|QtCore.Qt.InputMethodHint.ImhSensitiveData)
        self.line_password.setMaxLength(16)
        self.line_password.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.line_password.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.line_password.setObjectName("line_password")
        self.label_logo_721 = QtWidgets.QLabel(self.centralwidget)
        self.label_logo_721.setGeometry(QtCore.QRect(0, 0, 731, 721))
        self.label_logo_721.setText("")
        self.label_logo_721.setPixmap(QtGui.QPixmap("../images/logo_721.png"))
        self.label_logo_721.setScaledContents(False)
        self.label_logo_721.setObjectName("label_logo_721")
        self.label_login_password = QtWidgets.QLabel(self.centralwidget)
        self.label_login_password.setGeometry(QtCore.QRect(820, 150, 351, 20))
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(14)
        self.label_login_password.setFont(font)
        self.label_login_password.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.label_login_password.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_login_password.setObjectName("label_login_password")
        self.lable_suppot_text = QtWidgets.QLabel(self.centralwidget)
        self.lable_suppot_text.setGeometry(QtCore.QRect(830, 550, 341, 61))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.lable_suppot_text.setFont(font)
        self.lable_suppot_text.setMouseTracking(True)
        self.lable_suppot_text.setTabletTracking(False)
        self.lable_suppot_text.setAcceptDrops(False)
        self.lable_suppot_text.setTextFormat(QtCore.Qt.TextFormat.AutoText)
        self.lable_suppot_text.setScaledContents(False)
        self.lable_suppot_text.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lable_suppot_text.setWordWrap(True)
        self.lable_suppot_text.setObjectName("lable_suppot_text")
        self.label_version_text = QtWidgets.QLabel(self.centralwidget)
        self.label_version_text.setGeometry(QtCore.QRect(820, 660, 171, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.label_version_text.setFont(font)
        self.label_version_text.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.label_version_text.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_version_text.setObjectName("label_version_text")
        self.label_version_number = QtWidgets.QLabel(self.centralwidget)
        self.label_version_number.setGeometry(QtCore.QRect(1010, 660, 171, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.label_version_number.setFont(font)
        self.label_version_number.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.label_version_number.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_version_number.setObjectName("label_version_number")
        WindowAuthorization.setCentralWidget(self.centralwidget)

        self.retranslateUi(WindowAuthorization)
        QtCore.QMetaObject.connectSlotsByName(WindowAuthorization)

    def retranslateUi(self, WindowAuthorization):
        _translate = QtCore.QCoreApplication.translate
        WindowAuthorization.setWindowTitle(_translate("WindowAuthorization", "Малина 64"))
        self.btn_login.setText(_translate("WindowAuthorization", "Начать работу"))
        self.line_login.setPlaceholderText(_translate("WindowAuthorization", "Логин"))
        self.label_autor_text.setText(_translate("WindowAuthorization", "Автор логиcтических расчетов Китов А.О. \n"
" Разработчик Загуменкин П.И."))
        self.line_password.setPlaceholderText(_translate("WindowAuthorization", "Пароль"))
        self.label_login_password.setText(_translate("WindowAuthorization", "Введите логин и пароль"))
        self.lable_suppot_text.setText(_translate("WindowAuthorization", "По всем вопросам работы программы \n"
" обращаться в Отдел построения"))
        self.label_version_text.setText(_translate("WindowAuthorization", "Версия:"))
        self.label_version_number.setText(_translate("WindowAuthorization", "1.0"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    WindowAuthorization = QtWidgets.QMainWindow()
    ui = Ui_WindowAuthorization()
    ui.setupUi(WindowAuthorization)
    WindowAuthorization.show()
    sys.exit(app.exec())
