# Form implementation generated from reading ui file 'autozakaz_table.ui'
#
# Created by: PyQt6 UI code generator 6.3.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_autozakaz_table(object):
    def setupUi(self, autozakaz_table):
        autozakaz_table.setObjectName("autozakaz_table")
        autozakaz_table.resize(1203, 811)
        self.centralwidget = QtWidgets.QWidget(autozakaz_table)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.verticalLayout.addWidget(self.tableWidget)
        autozakaz_table.setCentralWidget(self.centralwidget)

        self.retranslateUi(autozakaz_table)
        QtCore.QMetaObject.connectSlotsByName(autozakaz_table)

    def retranslateUi(self, autozakaz_table):
        _translate = QtCore.QCoreApplication.translate
        autozakaz_table.setWindowTitle(_translate("autozakaz_table", "Работа с коэффициентами"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    autozakaz_table = QtWidgets.QMainWindow()
    ui = Ui_autozakaz_table()
    ui.setupUi(autozakaz_table)
    autozakaz_table.show()
    sys.exit(app.exec())
