# Form implementation generated from reading ui file 'bakery.ui'
#
# Created by: PyQt6 UI code generator 6.3.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_WindowBakery(object):
    def setupUi(self, WindowBakery):
        WindowBakery.setObjectName("WindowBakery")
        WindowBakery.setEnabled(True)
        WindowBakery.resize(1240, 700)
        WindowBakery.setMinimumSize(QtCore.QSize(1240, 700))
        WindowBakery.setMaximumSize(QtCore.QSize(1240, 700))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../image/icon.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        WindowBakery.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(WindowBakery)
        self.centralwidget.setEnabled(True)
        self.centralwidget.setObjectName("centralwidget")
        self.lineEdit_OLAP_dayWeek = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_OLAP_dayWeek.setEnabled(False)
        self.lineEdit_OLAP_dayWeek.setGeometry(QtCore.QRect(20, 350, 691, 51))
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(10)
        self.lineEdit_OLAP_dayWeek.setFont(font)
        self.lineEdit_OLAP_dayWeek.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.lineEdit_OLAP_dayWeek.setStyleSheet("padding-left: 5px")
        self.lineEdit_OLAP_dayWeek.setObjectName("lineEdit_OLAP_dayWeek")
        self.label_OLAP_prodagi = QtWidgets.QLabel(self.centralwidget)
        self.label_OLAP_prodagi.setGeometry(QtCore.QRect(20, 150, 771, 21))
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(12)
        self.label_OLAP_prodagi.setFont(font)
        self.label_OLAP_prodagi.setObjectName("label_OLAP_prodagi")
        self.lineEdit_OLAP_prodagi = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_OLAP_prodagi.setEnabled(False)
        self.lineEdit_OLAP_prodagi.setGeometry(QtCore.QRect(20, 180, 691, 51))
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(10)
        self.lineEdit_OLAP_prodagi.setFont(font)
        self.lineEdit_OLAP_prodagi.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.lineEdit_OLAP_prodagi.setStyleSheet("padding-left: 5px")
        self.lineEdit_OLAP_prodagi.setObjectName("lineEdit_OLAP_prodagi")
        self.btn_path_OLAP_prodagi = QtWidgets.QPushButton(self.centralwidget)
        self.btn_path_OLAP_prodagi.setGeometry(QtCore.QRect(730, 180, 51, 51))
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(22)
        font.setBold(False)
        font.setWeight(50)
        self.btn_path_OLAP_prodagi.setFont(font)
        self.btn_path_OLAP_prodagi.setStyleSheet("QPushButton {\n"
"background-color: rgb(228, 107, 134);\n"
"border: none;\n"
"border-radius: 10px}\n"
"\n"
"QPushButton:hover {\n"
"border: 1px solid  rgb(0, 0, 0);\n"
"background-color: rgba(228, 107, 134, 0.9)\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"border:3px solid  rgb(0, 0, 0);\n"
"background-color: rgba(228, 107, 134, 1)\n"
"}")
        self.btn_path_OLAP_prodagi.setCheckable(False)
        self.btn_path_OLAP_prodagi.setObjectName("btn_path_OLAP_prodagi")
        self.label_settings_title = QtWidgets.QLabel(self.centralwidget)
        self.label_settings_title.setGeometry(QtCore.QRect(20, 10, 631, 41))
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(20)
        self.label_settings_title.setFont(font)
        self.label_settings_title.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_settings_title.setObjectName("label_settings_title")
        self.label_OLAP_dayWeek = QtWidgets.QLabel(self.centralwidget)
        self.label_OLAP_dayWeek.setGeometry(QtCore.QRect(20, 320, 771, 21))
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(12)
        self.label_OLAP_dayWeek.setFont(font)
        self.label_OLAP_dayWeek.setObjectName("label_OLAP_dayWeek")
        self.btn_exit_bakery = QtWidgets.QPushButton(self.centralwidget)
        self.btn_exit_bakery.setGeometry(QtCore.QRect(820, 620, 391, 61))
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(22)
        font.setBold(False)
        font.setWeight(50)
        self.btn_exit_bakery.setFont(font)
        self.btn_exit_bakery.setStyleSheet("QPushButton {\n"
"background-color: rgb(228, 107, 134);\n"
"border: none;\n"
"border-radius: 10px}\n"
"\n"
"QPushButton:hover {\n"
"border: 1px solid  rgb(0, 0, 0);\n"
"background-color: rgba(228, 107, 134, 0.9)\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"border:3px solid  rgb(0, 0, 0);\n"
"background-color: rgba(228, 107, 134, 1)\n"
"}")
        self.btn_exit_bakery.setCheckable(False)
        self.btn_exit_bakery.setObjectName("btn_exit_bakery")
        self.btn_path_dayWeek = QtWidgets.QPushButton(self.centralwidget)
        self.btn_path_dayWeek.setGeometry(QtCore.QRect(730, 350, 51, 51))
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(22)
        font.setBold(False)
        font.setWeight(50)
        self.btn_path_dayWeek.setFont(font)
        self.btn_path_dayWeek.setStyleSheet("QPushButton {\n"
"background-color: rgb(228, 107, 134);\n"
"border: none;\n"
"border-radius: 10px}\n"
"\n"
"QPushButton:hover {\n"
"border: 1px solid  rgb(0, 0, 0);\n"
"background-color: rgba(228, 107, 134, 0.9)\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"border:3px solid  rgb(0, 0, 0);\n"
"background-color: rgba(228, 107, 134, 1)\n"
"}")
        self.btn_path_dayWeek.setCheckable(False)
        self.btn_path_dayWeek.setObjectName("btn_path_dayWeek")
        self.btn_set_prognoz = QtWidgets.QPushButton(self.centralwidget)
        self.btn_set_prognoz.setEnabled(False)
        self.btn_set_prognoz.setGeometry(QtCore.QRect(20, 240, 171, 51))
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.btn_set_prognoz.setFont(font)
        self.btn_set_prognoz.setStyleSheet("QPushButton {\n"
"background-color: rgb(228, 107, 134);\n"
"border: none;\n"
"border-radius: 10px}\n"
"\n"
"QPushButton:hover {\n"
"border: 1px solid  rgb(0, 0, 0);\n"
"background-color: rgba(228, 107, 134, 0.9)\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"border:3px solid  rgb(0, 0, 0);\n"
"background-color: rgba(228, 107, 134, 1)\n"
"}")
        self.btn_set_prognoz.setCheckable(False)
        self.btn_set_prognoz.setObjectName("btn_set_prognoz")
        self.label_startDay_and_endDay = QtWidgets.QLabel(self.centralwidget)
        self.label_startDay_and_endDay.setGeometry(QtCore.QRect(20, 60, 691, 21))
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(12)
        self.label_startDay_and_endDay.setFont(font)
        self.label_startDay_and_endDay.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_startDay_and_endDay.setObjectName("label_startDay_and_endDay")
        self.label_startDay = QtWidgets.QLabel(self.centralwidget)
        self.label_startDay.setGeometry(QtCore.QRect(20, 100, 141, 41))
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(12)
        self.label_startDay.setFont(font)
        self.label_startDay.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.label_startDay.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_startDay.setObjectName("label_startDay")
        self.label_endDay = QtWidgets.QLabel(self.centralwidget)
        self.label_endDay.setGeometry(QtCore.QRect(320, 100, 141, 41))
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(12)
        self.label_endDay.setFont(font)
        self.label_endDay.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_endDay.setObjectName("label_endDay")
        self.dateEdit_startDay = QtWidgets.QDateEdit(self.centralwidget)
        self.dateEdit_startDay.setGeometry(QtCore.QRect(170, 100, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.dateEdit_startDay.setFont(font)
        self.dateEdit_startDay.setCalendarPopup(True)
        self.dateEdit_startDay.setTimeSpec(QtCore.Qt.TimeSpec.LocalTime)
        self.dateEdit_startDay.setObjectName("dateEdit_startDay")
        self.dateEdit_endDay = QtWidgets.QDateEdit(self.centralwidget)
        self.dateEdit_endDay.setEnabled(False)
        self.dateEdit_endDay.setGeometry(QtCore.QRect(460, 100, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.dateEdit_endDay.setFont(font)
        self.dateEdit_endDay.setCalendarPopup(True)
        self.dateEdit_endDay.setObjectName("dateEdit_endDay")
        self.btn_prosmotr_prognoz = QtWidgets.QPushButton(self.centralwidget)
        self.btn_prosmotr_prognoz.setEnabled(False)
        self.btn_prosmotr_prognoz.setGeometry(QtCore.QRect(210, 240, 181, 51))
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.btn_prosmotr_prognoz.setFont(font)
        self.btn_prosmotr_prognoz.setStyleSheet("QPushButton {\n"
"background-color: rgb(228, 107, 134);\n"
"border: none;\n"
"border-radius: 10px}\n"
"\n"
"QPushButton:hover {\n"
"border: 1px solid  rgb(0, 0, 0);\n"
"background-color: rgba(228, 107, 134, 0.9)\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"border:3px solid  rgb(0, 0, 0);\n"
"background-color: rgba(228, 107, 134, 1)\n"
"}")
        self.btn_prosmotr_prognoz.setCheckable(False)
        self.btn_prosmotr_prognoz.setObjectName("btn_prosmotr_prognoz")
        self.btn_edit_prognoz = QtWidgets.QPushButton(self.centralwidget)
        self.btn_edit_prognoz.setEnabled(False)
        self.btn_edit_prognoz.setGeometry(QtCore.QRect(410, 240, 171, 51))
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.btn_edit_prognoz.setFont(font)
        self.btn_edit_prognoz.setStyleSheet("QPushButton {\n"
"background-color: rgb(228, 107, 134);\n"
"border: none;\n"
"border-radius: 10px}\n"
"\n"
"QPushButton:hover {\n"
"border: 1px solid  rgb(0, 0, 0);\n"
"background-color: rgba(228, 107, 134, 0.9)\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"border:3px solid  rgb(0, 0, 0);\n"
"background-color: rgba(228, 107, 134, 1)\n"
"}")
        self.btn_edit_prognoz.setCheckable(False)
        self.btn_edit_prognoz.setObjectName("btn_edit_prognoz")
        self.btn_edit_normativ = QtWidgets.QPushButton(self.centralwidget)
        self.btn_edit_normativ.setEnabled(False)
        self.btn_edit_normativ.setGeometry(QtCore.QRect(280, 540, 241, 61))
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(22)
        font.setBold(False)
        font.setWeight(50)
        self.btn_edit_normativ.setFont(font)
        self.btn_edit_normativ.setStyleSheet("QPushButton {\n"
"background-color: rgb(228, 107, 134);\n"
"border: none;\n"
"border-radius: 10px}\n"
"\n"
"QPushButton:hover {\n"
"border: 1px solid  rgb(0, 0, 0);\n"
"background-color: rgba(228, 107, 134, 0.9)\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"border:3px solid  rgb(0, 0, 0);\n"
"background-color: rgba(228, 107, 134, 1)\n"
"}")
        self.btn_edit_normativ.setCheckable(False)
        self.btn_edit_normativ.setObjectName("btn_edit_normativ")
        self.btn_set_normativ = QtWidgets.QPushButton(self.centralwidget)
        self.btn_set_normativ.setEnabled(False)
        self.btn_set_normativ.setGeometry(QtCore.QRect(20, 540, 231, 61))
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.btn_set_normativ.setFont(font)
        self.btn_set_normativ.setStyleSheet("QPushButton {\n"
"background-color: rgb(228, 107, 134);\n"
"border: none;\n"
"border-radius: 10px}\n"
"\n"
"QPushButton:hover {\n"
"border: 1px solid  rgb(0, 0, 0);\n"
"background-color: rgba(228, 107, 134, 0.9)\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"border:3px solid  rgb(0, 0, 0);\n"
"background-color: rgba(228, 107, 134, 1)\n"
"}")
        self.btn_set_normativ.setCheckable(False)
        self.btn_set_normativ.setObjectName("btn_set_normativ")
        self.btn_edit_dayWeek = QtWidgets.QPushButton(self.centralwidget)
        self.btn_edit_dayWeek.setEnabled(False)
        self.btn_edit_dayWeek.setGeometry(QtCore.QRect(410, 410, 171, 51))
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.btn_edit_dayWeek.setFont(font)
        self.btn_edit_dayWeek.setStyleSheet("QPushButton {\n"
"background-color: rgb(228, 107, 134);\n"
"border: none;\n"
"border-radius: 10px}\n"
"\n"
"QPushButton:hover {\n"
"border: 1px solid  rgb(0, 0, 0);\n"
"background-color: rgba(228, 107, 134, 0.9)\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"border:3px solid  rgb(0, 0, 0);\n"
"background-color: rgba(228, 107, 134, 1)\n"
"}")
        self.btn_edit_dayWeek.setCheckable(False)
        self.btn_edit_dayWeek.setObjectName("btn_edit_dayWeek")
        self.btn_download_normativ = QtWidgets.QPushButton(self.centralwidget)
        self.btn_download_normativ.setEnabled(False)
        self.btn_download_normativ.setGeometry(QtCore.QRect(820, 480, 391, 61))
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.btn_download_normativ.setFont(font)
        self.btn_download_normativ.setStyleSheet("QPushButton {\n"
"background-color: rgb(228, 107, 134);\n"
"border: none;\n"
"border-radius: 10px}\n"
"\n"
"QPushButton:hover {\n"
"border: 1px solid  rgb(0, 0, 0);\n"
"background-color: rgba(228, 107, 134, 0.9)\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"border:3px solid  rgb(0, 0, 0);\n"
"background-color: rgba(228, 107, 134, 1)\n"
"}")
        self.btn_download_normativ.setCheckable(False)
        self.btn_download_normativ.setObjectName("btn_download_normativ")
        self.label_konditerskie = QtWidgets.QLabel(self.centralwidget)
        self.label_konditerskie.setGeometry(QtCore.QRect(830, 20, 381, 31))
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(12)
        self.label_konditerskie.setFont(font)
        self.label_konditerskie.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_konditerskie.setObjectName("label_konditerskie")
        self.line_1 = QtWidgets.QFrame(self.centralwidget)
        self.line_1.setGeometry(QtCore.QRect(820, 10, 401, 21))
        self.line_1.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_1.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_1.setObjectName("line_1")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(820, 460, 401, 21))
        self.line_2.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setGeometry(QtCore.QRect(1210, 20, 20, 451))
        self.line_3.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_3.setObjectName("line_3")
        self.line_4 = QtWidgets.QFrame(self.centralwidget)
        self.line_4.setGeometry(QtCore.QRect(810, 20, 20, 451))
        self.line_4.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_4.setObjectName("line_4")
        self.btn_prosmotr_dayWeek = QtWidgets.QPushButton(self.centralwidget)
        self.btn_prosmotr_dayWeek.setEnabled(False)
        self.btn_prosmotr_dayWeek.setGeometry(QtCore.QRect(210, 410, 181, 51))
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.btn_prosmotr_dayWeek.setFont(font)
        self.btn_prosmotr_dayWeek.setStyleSheet("QPushButton {\n"
"background-color: rgb(228, 107, 134);\n"
"border: none;\n"
"border-radius: 10px}\n"
"\n"
"QPushButton:hover {\n"
"border: 1px solid  rgb(0, 0, 0);\n"
"background-color: rgba(228, 107, 134, 0.9)\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"border:3px solid  rgb(0, 0, 0);\n"
"background-color: rgba(228, 107, 134, 1)\n"
"}")
        self.btn_prosmotr_dayWeek.setCheckable(False)
        self.btn_prosmotr_dayWeek.setObjectName("btn_prosmotr_dayWeek")
        self.btn_delete_prognoz = QtWidgets.QPushButton(self.centralwidget)
        self.btn_delete_prognoz.setEnabled(False)
        self.btn_delete_prognoz.setGeometry(QtCore.QRect(600, 240, 181, 51))
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.btn_delete_prognoz.setFont(font)
        self.btn_delete_prognoz.setStyleSheet("QPushButton {\n"
"background-color: rgb(228, 107, 134);\n"
"border: none;\n"
"border-radius: 10px}\n"
"\n"
"QPushButton:hover {\n"
"border: 1px solid  rgb(0, 0, 0);\n"
"background-color: rgba(228, 107, 134, 0.9)\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"border:3px solid  rgb(0, 0, 0);\n"
"background-color: rgba(228, 107, 134, 1)\n"
"}")
        self.btn_delete_prognoz.setCheckable(False)
        self.btn_delete_prognoz.setObjectName("btn_delete_prognoz")
        self.btn_delete_dayWeek = QtWidgets.QPushButton(self.centralwidget)
        self.btn_delete_dayWeek.setEnabled(False)
        self.btn_delete_dayWeek.setGeometry(QtCore.QRect(600, 410, 181, 51))
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.btn_delete_dayWeek.setFont(font)
        self.btn_delete_dayWeek.setStyleSheet("QPushButton {\n"
"background-color: rgb(228, 107, 134);\n"
"border: none;\n"
"border-radius: 10px}\n"
"\n"
"QPushButton:hover {\n"
"border: 1px solid  rgb(0, 0, 0);\n"
"background-color: rgba(228, 107, 134, 0.9)\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"border:3px solid  rgb(0, 0, 0);\n"
"background-color: rgba(228, 107, 134, 1)\n"
"}")
        self.btn_delete_dayWeek.setCheckable(False)
        self.btn_delete_dayWeek.setObjectName("btn_delete_dayWeek")
        self.btn_set_dayWeek = QtWidgets.QPushButton(self.centralwidget)
        self.btn_set_dayWeek.setEnabled(False)
        self.btn_set_dayWeek.setGeometry(QtCore.QRect(20, 410, 171, 51))
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.btn_set_dayWeek.setFont(font)
        self.btn_set_dayWeek.setStyleSheet("QPushButton {\n"
"background-color: rgb(228, 107, 134);\n"
"border: none;\n"
"border-radius: 10px}\n"
"\n"
"QPushButton:hover {\n"
"border: 1px solid  rgb(0, 0, 0);\n"
"background-color: rgba(228, 107, 134, 0.9)\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"border:3px solid  rgb(0, 0, 0);\n"
"background-color: rgba(228, 107, 134, 1)\n"
"}")
        self.btn_set_dayWeek.setCheckable(False)
        self.btn_set_dayWeek.setObjectName("btn_set_dayWeek")
        self.formLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.formLayoutWidget.setGeometry(QtCore.QRect(830, 50, 381, 411))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.gridPoints = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.gridPoints.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetDefaultConstraint)
        self.gridPoints.setFieldGrowthPolicy(QtWidgets.QFormLayout.FieldGrowthPolicy.FieldsStayAtSizeHint)
        self.gridPoints.setRowWrapPolicy(QtWidgets.QFormLayout.RowWrapPolicy.WrapLongRows)
        self.gridPoints.setLabelAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.gridPoints.setFormAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.gridPoints.setContentsMargins(15, 5, 0, 0)
        self.gridPoints.setHorizontalSpacing(40)
        self.gridPoints.setVerticalSpacing(7)
        self.gridPoints.setObjectName("gridPoints")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(10, 140, 781, 20))
        self.line.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line.setObjectName("line")
        self.line_5 = QtWidgets.QFrame(self.centralwidget)
        self.line_5.setGeometry(QtCore.QRect(10, 290, 781, 20))
        self.line_5.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_5.setObjectName("line_5")
        self.line_6 = QtWidgets.QFrame(self.centralwidget)
        self.line_6.setGeometry(QtCore.QRect(780, 150, 20, 151))
        self.line_6.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_6.setObjectName("line_6")
        self.line_7 = QtWidgets.QFrame(self.centralwidget)
        self.line_7.setGeometry(QtCore.QRect(0, 150, 20, 151))
        self.line_7.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_7.setObjectName("line_7")
        self.line_8 = QtWidgets.QFrame(self.centralwidget)
        self.line_8.setGeometry(QtCore.QRect(780, 320, 20, 151))
        self.line_8.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_8.setObjectName("line_8")
        self.line_9 = QtWidgets.QFrame(self.centralwidget)
        self.line_9.setGeometry(QtCore.QRect(10, 310, 781, 20))
        self.line_9.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_9.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_9.setObjectName("line_9")
        self.line_10 = QtWidgets.QFrame(self.centralwidget)
        self.line_10.setGeometry(QtCore.QRect(10, 460, 781, 20))
        self.line_10.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_10.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_10.setObjectName("line_10")
        self.line_11 = QtWidgets.QFrame(self.centralwidget)
        self.line_11.setGeometry(QtCore.QRect(0, 320, 20, 151))
        self.line_11.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line_11.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_11.setObjectName("line_11")
        self.btn_delete_normativ = QtWidgets.QPushButton(self.centralwidget)
        self.btn_delete_normativ.setEnabled(False)
        self.btn_delete_normativ.setGeometry(QtCore.QRect(550, 540, 231, 61))
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(22)
        font.setBold(False)
        font.setWeight(50)
        self.btn_delete_normativ.setFont(font)
        self.btn_delete_normativ.setStyleSheet("QPushButton {\n"
"background-color: rgb(228, 107, 134);\n"
"border: none;\n"
"border-radius: 10px}\n"
"\n"
"QPushButton:hover {\n"
"border: 1px solid  rgb(0, 0, 0);\n"
"background-color: rgba(228, 107, 134, 0.9)\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"border:3px solid  rgb(0, 0, 0);\n"
"background-color: rgba(228, 107, 134, 1)\n"
"}")
        self.btn_delete_normativ.setCheckable(False)
        self.btn_delete_normativ.setObjectName("btn_delete_normativ")
        self.label_normativs = QtWidgets.QLabel(self.centralwidget)
        self.label_normativs.setGeometry(QtCore.QRect(30, 500, 761, 21))
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(15)
        self.label_normativs.setFont(font)
        self.label_normativs.setObjectName("label_normativs")
        self.line_12 = QtWidgets.QFrame(self.centralwidget)
        self.line_12.setGeometry(QtCore.QRect(10, 480, 781, 20))
        self.line_12.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_12.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_12.setObjectName("line_12")
        self.line_13 = QtWidgets.QFrame(self.centralwidget)
        self.line_13.setGeometry(QtCore.QRect(10, 610, 781, 20))
        self.line_13.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_13.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_13.setObjectName("line_13")
        self.line_14 = QtWidgets.QFrame(self.centralwidget)
        self.line_14.setGeometry(QtCore.QRect(780, 490, 20, 131))
        self.line_14.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line_14.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_14.setObjectName("line_14")
        self.line_15 = QtWidgets.QFrame(self.centralwidget)
        self.line_15.setGeometry(QtCore.QRect(0, 490, 20, 131))
        self.line_15.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line_15.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_15.setObjectName("line_15")
        self.btn_download_layout = QtWidgets.QPushButton(self.centralwidget)
        self.btn_download_layout.setEnabled(False)
        self.btn_download_layout.setGeometry(QtCore.QRect(820, 550, 391, 61))
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.btn_download_layout.setFont(font)
        self.btn_download_layout.setStyleSheet("QPushButton {\n"
"background-color: rgb(228, 107, 134);\n"
"border: none;\n"
"border-radius: 10px}\n"
"\n"
"QPushButton:hover {\n"
"border: 1px solid  rgb(0, 0, 0);\n"
"background-color: rgba(228, 107, 134, 0.9)\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"border:3px solid  rgb(0, 0, 0);\n"
"background-color: rgba(228, 107, 134, 1)\n"
"}")
        self.btn_download_layout.setCheckable(False)
        self.btn_download_layout.setObjectName("btn_download_layout")
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setEnabled(True)
        self.progressBar.setGeometry(QtCore.QRect(290, 330, 600, 40))
        self.progressBar.setMinimumSize(QtCore.QSize(600, 40))
        self.progressBar.setMaximumSize(QtCore.QSize(600, 40))
        self.progressBar.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setTextVisible(False)
        self.progressBar.setInvertedAppearance(False)
        self.progressBar.setTextDirection(QtWidgets.QProgressBar.Direction.TopToBottom)
        self.progressBar.setObjectName("progressBar")
        WindowBakery.setCentralWidget(self.centralwidget)

        self.retranslateUi(WindowBakery)
        QtCore.QMetaObject.connectSlotsByName(WindowBakery)

    def retranslateUi(self, WindowBakery):
        _translate = QtCore.QCoreApplication.translate
        WindowBakery.setWindowTitle(_translate("WindowBakery", "Настройка работы с Выпечкой"))
        self.label_OLAP_prodagi.setText(_translate("WindowBakery", "Укажите путь к OLAP отчету по продажам выпечки"))
        self.btn_path_OLAP_prodagi.setText(_translate("WindowBakery", "..."))
        self.label_settings_title.setText(_translate("WindowBakery", "Настройка подключения внешних данных"))
        self.label_OLAP_dayWeek.setText(_translate("WindowBakery", "Укажите путь к OLAP отчету по продажам по дням недели по выпечке"))
        self.btn_exit_bakery.setText(_translate("WindowBakery", "К ВЫБОРУ РАЗДЕЛА"))
        self.btn_path_dayWeek.setText(_translate("WindowBakery", "..."))
        self.btn_set_prognoz.setText(_translate("WindowBakery", "Установить"))
        self.label_startDay_and_endDay.setText(_translate("WindowBakery", "Укажите начало периода для формирования данных"))
        self.label_startDay.setText(_translate("WindowBakery", "Начало периода"))
        self.label_endDay.setText(_translate("WindowBakery", "Конец периода"))
        self.btn_prosmotr_prognoz.setText(_translate("WindowBakery", "Посмотреть"))
        self.btn_edit_prognoz.setText(_translate("WindowBakery", "Редактировать"))
        self.btn_edit_normativ.setText(_translate("WindowBakery", "Редактировать"))
        self.btn_set_normativ.setText(_translate("WindowBakery", "Установить"))
        self.btn_edit_dayWeek.setText(_translate("WindowBakery", "Редактировать"))
        self.btn_download_normativ.setText(_translate("WindowBakery", "ВЫГРУЗИТЬ НОРМАТИВЫ"))
        self.label_konditerskie.setText(_translate("WindowBakery", "Выберите кондитерские для автозаказа"))
        self.btn_prosmotr_dayWeek.setText(_translate("WindowBakery", "Посмотреть"))
        self.btn_delete_prognoz.setText(_translate("WindowBakery", "Удалить"))
        self.btn_delete_dayWeek.setText(_translate("WindowBakery", "Удалить"))
        self.btn_set_dayWeek.setText(_translate("WindowBakery", "Установить"))
        self.btn_delete_normativ.setText(_translate("WindowBakery", "Удалить"))
        self.label_normativs.setText(_translate("WindowBakery", "Нормативы пекарни"))
        self.btn_download_layout.setText(_translate("WindowBakery", "ВЫГРУЗИТЬ ВЫКЛАДКУ"))
        self.progressBar.setFormat(_translate("WindowBakery", "%p%"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    WindowBakery = QtWidgets.QMainWindow()
    ui = Ui_WindowBakery()
    ui.setupUi(WindowBakery)
    WindowBakery.show()
    sys.exit(app.exec())
