# Form implementation generated from reading ui file 'logistics.ui'
#
# Created by: PyQt6 UI code generator 6.3.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_WindowLogistics(object):
    def setupUi(self, WindowLogistics):
        WindowLogistics.setObjectName("WindowLogistics")
        WindowLogistics.resize(370, 600)
        self.centralwidget = QtWidgets.QWidget(WindowLogistics)
        self.centralwidget.setMinimumSize(QtCore.QSize(370, 600))
        self.centralwidget.setMaximumSize(QtCore.QSize(370, 600))
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_title = QtWidgets.QLabel(self.centralwidget)
        self.label_title.setMaximumSize(QtCore.QSize(16777215, 60))
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(20)
        self.label_title.setFont(font)
        self.label_title.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.label_title.setScaledContents(True)
        self.label_title.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_title.setWordWrap(False)
        self.label_title.setObjectName("label_title")
        self.verticalLayout.addWidget(self.label_title)
        self.btn_autoorders = QtWidgets.QPushButton(self.centralwidget)
        self.btn_autoorders.setEnabled(True)
        self.btn_autoorders.setMinimumSize(QtCore.QSize(0, 65))
        self.btn_autoorders.setMaximumSize(QtCore.QSize(500, 65))
        self.btn_autoorders.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(22)
        font.setBold(False)
        font.setWeight(50)
        self.btn_autoorders.setFont(font)
        self.btn_autoorders.setStyleSheet("QPushButton {\n"
"background-color: rgb(228, 107, 134);\n"
"border: none;\n"
"border-radius: 10px}\n"
"\n"
"QPushButton:hover {\n"
"border: 1px solid  rgb(0, 0, 0);\n"
"background-color: rgba(228, 107, 134, 0.9)\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"border:3px solid  rgb(0, 0, 0);\n"
"background-color: rgba(228, 107, 134, 1)\n"
"}")
        self.btn_autoorders.setCheckable(False)
        self.btn_autoorders.setObjectName("btn_autoorders")
        self.verticalLayout.addWidget(self.btn_autoorders)
        self.btn_comingsoon4 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_comingsoon4.setEnabled(True)
        self.btn_comingsoon4.setMinimumSize(QtCore.QSize(0, 65))
        self.btn_comingsoon4.setMaximumSize(QtCore.QSize(500, 65))
        self.btn_comingsoon4.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(22)
        font.setBold(False)
        font.setWeight(50)
        self.btn_comingsoon4.setFont(font)
        self.btn_comingsoon4.setStyleSheet("QPushButton {\n"
"background-color: rgb(228, 107, 134);\n"
"border: none;\n"
"border-radius: 10px}\n"
"\n"
"QPushButton:hover {\n"
"border: 1px solid  rgb(0, 0, 0);\n"
"background-color: rgba(228, 107, 134, 0.9)\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"border:3px solid  rgb(0, 0, 0);\n"
"background-color: rgba(228, 107, 134, 1)\n"
"}")
        self.btn_comingsoon4.setCheckable(False)
        self.btn_comingsoon4.setObjectName("btn_comingsoon4")
        self.verticalLayout.addWidget(self.btn_comingsoon4)
        self.btn_comingsoon1 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_comingsoon1.setEnabled(True)
        self.btn_comingsoon1.setMinimumSize(QtCore.QSize(0, 65))
        self.btn_comingsoon1.setMaximumSize(QtCore.QSize(500, 65))
        self.btn_comingsoon1.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(22)
        font.setBold(False)
        font.setWeight(50)
        self.btn_comingsoon1.setFont(font)
        self.btn_comingsoon1.setStyleSheet("QPushButton {\n"
"background-color: rgb(228, 107, 134);\n"
"border: none;\n"
"border-radius: 10px}\n"
"\n"
"QPushButton:hover {\n"
"border: 1px solid  rgb(0, 0, 0);\n"
"background-color: rgba(228, 107, 134, 0.9)\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"border:3px solid  rgb(0, 0, 0);\n"
"background-color: rgba(228, 107, 134, 1)\n"
"}")
        self.btn_comingsoon1.setCheckable(False)
        self.btn_comingsoon1.setObjectName("btn_comingsoon1")
        self.verticalLayout.addWidget(self.btn_comingsoon1)
        self.btn_comingsoon2 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_comingsoon2.setEnabled(True)
        self.btn_comingsoon2.setMinimumSize(QtCore.QSize(0, 65))
        self.btn_comingsoon2.setMaximumSize(QtCore.QSize(500, 65))
        self.btn_comingsoon2.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(22)
        font.setBold(False)
        font.setWeight(50)
        self.btn_comingsoon2.setFont(font)
        self.btn_comingsoon2.setStyleSheet("QPushButton {\n"
"background-color: rgb(228, 107, 134);\n"
"border: none;\n"
"border-radius: 10px}\n"
"\n"
"QPushButton:hover {\n"
"border: 1px solid  rgb(0, 0, 0);\n"
"background-color: rgba(228, 107, 134, 0.9)\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"border:3px solid  rgb(0, 0, 0);\n"
"background-color: rgba(228, 107, 134, 1)\n"
"}")
        self.btn_comingsoon2.setCheckable(False)
        self.btn_comingsoon2.setObjectName("btn_comingsoon2")
        self.verticalLayout.addWidget(self.btn_comingsoon2)
        self.btn_comingsoon3 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_comingsoon3.setEnabled(True)
        self.btn_comingsoon3.setMinimumSize(QtCore.QSize(0, 65))
        self.btn_comingsoon3.setMaximumSize(QtCore.QSize(500, 65))
        self.btn_comingsoon3.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(22)
        font.setBold(False)
        font.setWeight(50)
        self.btn_comingsoon3.setFont(font)
        self.btn_comingsoon3.setStyleSheet("QPushButton {\n"
"background-color: rgb(228, 107, 134);\n"
"border: none;\n"
"border-radius: 10px}\n"
"\n"
"QPushButton:hover {\n"
"border: 1px solid  rgb(0, 0, 0);\n"
"background-color: rgba(228, 107, 134, 0.9)\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"border:3px solid  rgb(0, 0, 0);\n"
"background-color: rgba(228, 107, 134, 1)\n"
"}")
        self.btn_comingsoon3.setCheckable(False)
        self.btn_comingsoon3.setObjectName("btn_comingsoon3")
        self.verticalLayout.addWidget(self.btn_comingsoon3)
        self.btn_back = QtWidgets.QPushButton(self.centralwidget)
        self.btn_back.setEnabled(True)
        self.btn_back.setMinimumSize(QtCore.QSize(0, 65))
        self.btn_back.setMaximumSize(QtCore.QSize(500, 65))
        self.btn_back.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(22)
        font.setBold(False)
        font.setWeight(50)
        self.btn_back.setFont(font)
        self.btn_back.setStyleSheet("QPushButton {\n"
"background-color: rgb(228, 107, 134);\n"
"border: none;\n"
"border-radius: 10px}\n"
"\n"
"QPushButton:hover {\n"
"border: 1px solid  rgb(0, 0, 0);\n"
"background-color: rgba(228, 107, 134, 0.9)\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"border:3px solid  rgb(0, 0, 0);\n"
"background-color: rgba(228, 107, 134, 1)\n"
"}")
        self.btn_back.setCheckable(False)
        self.btn_back.setObjectName("btn_back")
        self.verticalLayout.addWidget(self.btn_back)
        WindowLogistics.setCentralWidget(self.centralwidget)

        self.retranslateUi(WindowLogistics)
        QtCore.QMetaObject.connectSlotsByName(WindowLogistics)

    def retranslateUi(self, WindowLogistics):
        _translate = QtCore.QCoreApplication.translate
        WindowLogistics.setWindowTitle(_translate("WindowLogistics", "Выберите раздел"))
        self.label_title.setText(_translate("WindowLogistics", "Выберите раздел"))
        self.btn_autoorders.setText(_translate("WindowLogistics", "АВТОЗАКАЗЫ"))
        self.btn_comingsoon4.setText(_translate("WindowLogistics", "В РАЗРАБОТКЕ"))
        self.btn_comingsoon1.setText(_translate("WindowLogistics", "В РАЗРАБОТКЕ"))
        self.btn_comingsoon2.setText(_translate("WindowLogistics", "В РАЗРАБОТКЕ"))
        self.btn_comingsoon3.setText(_translate("WindowLogistics", "В РАЗРАБОТКЕ"))
        self.btn_back.setText(_translate("WindowLogistics", "НАЗАД"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    WindowLogistics = QtWidgets.QMainWindow()
    ui = Ui_WindowLogistics()
    ui.setupUi(WindowLogistics)
    WindowLogistics.show()
    sys.exit(app.exec())
