# Form implementation generated from reading ui file 'nomenklatura.ui'
#
# Created by: PyQt6 UI code generator 6.3.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_WindowNomenklatura(object):
    def setupUi(self, WindowNomenklatura):
        WindowNomenklatura.setObjectName("WindowNomenklatura")
        WindowNomenklatura.resize(370, 600)
        self.centralwidget = QtWidgets.QWidget(WindowNomenklatura)
        self.centralwidget.setMinimumSize(QtCore.QSize(370, 600))
        self.centralwidget.setMaximumSize(QtCore.QSize(370, 600))
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_title = QtWidgets.QLabel(self.centralwidget)
        self.label_title.setMaximumSize(QtCore.QSize(16777215, 60))
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(20)
        self.label_title.setFont(font)
        self.label_title.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.label_title.setScaledContents(True)
        self.label_title.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_title.setWordWrap(False)
        self.label_title.setObjectName("label_title")
        self.verticalLayout.addWidget(self.label_title)
        self.btn_dishe = QtWidgets.QPushButton(self.centralwidget)
        self.btn_dishe.setEnabled(True)
        self.btn_dishe.setMinimumSize(QtCore.QSize(0, 65))
        self.btn_dishe.setMaximumSize(QtCore.QSize(500, 65))
        self.btn_dishe.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(22)
        font.setBold(False)
        self.btn_dishe.setFont(font)
        self.btn_dishe.setStyleSheet("QPushButton {\n"
"background-color: rgb(228, 107, 134);\n"
"border: none;\n"
"border-radius: 10px}\n"
"\n"
"QPushButton:hover {\n"
"border: 1px solid  rgb(0, 0, 0);\n"
"background-color: rgba(228, 107, 134, 0.9)\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"border:3px solid  rgb(0, 0, 0);\n"
"background-color: rgba(228, 107, 134, 1)\n"
"}")
        self.btn_dishe.setCheckable(False)
        self.btn_dishe.setObjectName("btn_dishe")
        self.verticalLayout.addWidget(self.btn_dishe)
        self.btn_pf = QtWidgets.QPushButton(self.centralwidget)
        self.btn_pf.setEnabled(True)
        self.btn_pf.setMinimumSize(QtCore.QSize(0, 65))
        self.btn_pf.setMaximumSize(QtCore.QSize(500, 65))
        self.btn_pf.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(22)
        font.setBold(False)
        self.btn_pf.setFont(font)
        self.btn_pf.setStyleSheet("QPushButton {\n"
"background-color: rgb(228, 107, 134);\n"
"border: none;\n"
"border-radius: 10px}\n"
"\n"
"QPushButton:hover {\n"
"border: 1px solid  rgb(0, 0, 0);\n"
"background-color: rgba(228, 107, 134, 0.9)\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"border:3px solid  rgb(0, 0, 0);\n"
"background-color: rgba(228, 107, 134, 1)\n"
"}")
        self.btn_pf.setCheckable(False)
        self.btn_pf.setObjectName("btn_pf")
        self.verticalLayout.addWidget(self.btn_pf)
        self.btn_materials = QtWidgets.QPushButton(self.centralwidget)
        self.btn_materials.setEnabled(True)
        self.btn_materials.setMinimumSize(QtCore.QSize(0, 65))
        self.btn_materials.setMaximumSize(QtCore.QSize(500, 65))
        self.btn_materials.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(22)
        font.setBold(False)
        self.btn_materials.setFont(font)
        self.btn_materials.setStyleSheet("QPushButton {\n"
"background-color: rgb(228, 107, 134);\n"
"border: none;\n"
"border-radius: 10px}\n"
"\n"
"QPushButton:hover {\n"
"border: 1px solid  rgb(0, 0, 0);\n"
"background-color: rgba(228, 107, 134, 0.9)\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"border:3px solid  rgb(0, 0, 0);\n"
"background-color: rgba(228, 107, 134, 1)\n"
"}")
        self.btn_materials.setCheckable(False)
        self.btn_materials.setObjectName("btn_materials")
        self.verticalLayout.addWidget(self.btn_materials)
        self.btn_4 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_4.setEnabled(True)
        self.btn_4.setMinimumSize(QtCore.QSize(0, 65))
        self.btn_4.setMaximumSize(QtCore.QSize(500, 65))
        self.btn_4.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(22)
        font.setBold(False)
        self.btn_4.setFont(font)
        self.btn_4.setStyleSheet("QPushButton {\n"
"background-color: rgb(228, 107, 134);\n"
"border: none;\n"
"border-radius: 10px}\n"
"\n"
"QPushButton:hover {\n"
"border: 1px solid  rgb(0, 0, 0);\n"
"background-color: rgba(228, 107, 134, 0.9)\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"border:3px solid  rgb(0, 0, 0);\n"
"background-color: rgba(228, 107, 134, 1)\n"
"}")
        self.btn_4.setCheckable(False)
        self.btn_4.setObjectName("btn_4")
        self.verticalLayout.addWidget(self.btn_4)
        self.btn_5 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_5.setEnabled(True)
        self.btn_5.setMinimumSize(QtCore.QSize(0, 65))
        self.btn_5.setMaximumSize(QtCore.QSize(500, 65))
        self.btn_5.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(22)
        font.setBold(False)
        self.btn_5.setFont(font)
        self.btn_5.setStyleSheet("QPushButton {\n"
"background-color: rgb(228, 107, 134);\n"
"border: none;\n"
"border-radius: 10px}\n"
"\n"
"QPushButton:hover {\n"
"border: 1px solid  rgb(0, 0, 0);\n"
"background-color: rgba(228, 107, 134, 0.9)\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"border:3px solid  rgb(0, 0, 0);\n"
"background-color: rgba(228, 107, 134, 1)\n"
"}")
        self.btn_5.setCheckable(False)
        self.btn_5.setObjectName("btn_5")
        self.verticalLayout.addWidget(self.btn_5)
        self.btn_back = QtWidgets.QPushButton(self.centralwidget)
        self.btn_back.setEnabled(True)
        self.btn_back.setMinimumSize(QtCore.QSize(0, 65))
        self.btn_back.setMaximumSize(QtCore.QSize(500, 65))
        self.btn_back.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(22)
        font.setBold(False)
        self.btn_back.setFont(font)
        self.btn_back.setStyleSheet("QPushButton {\n"
"background-color: rgb(228, 107, 134);\n"
"border: none;\n"
"border-radius: 10px}\n"
"\n"
"QPushButton:hover {\n"
"border: 1px solid  rgb(0, 0, 0);\n"
"background-color: rgba(228, 107, 134, 0.9)\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"border:3px solid  rgb(0, 0, 0);\n"
"background-color: rgba(228, 107, 134, 1)\n"
"}")
        self.btn_back.setCheckable(False)
        self.btn_back.setObjectName("btn_back")
        self.verticalLayout.addWidget(self.btn_back)
        WindowNomenklatura.setCentralWidget(self.centralwidget)

        self.retranslateUi(WindowNomenklatura)
        QtCore.QMetaObject.connectSlotsByName(WindowNomenklatura)

    def retranslateUi(self, WindowNomenklatura):
        _translate = QtCore.QCoreApplication.translate
        WindowNomenklatura.setWindowTitle(_translate("WindowNomenklatura", "Выберите раздел"))
        self.label_title.setText(_translate("WindowNomenklatura", "Выберите раздел"))
        self.btn_dishe.setText(_translate("WindowNomenklatura", "БЛЮДА"))
        self.btn_pf.setText(_translate("WindowNomenklatura", "ПОЛУФАБРИКАТЫ"))
        self.btn_materials.setText(_translate("WindowNomenklatura", "СЫРЬЕ"))
        self.btn_4.setText(_translate("WindowNomenklatura", "В РАЗРАБОТКЕ"))
        self.btn_5.setText(_translate("WindowNomenklatura", "В РАЗРАБОТКЕ"))
        self.btn_back.setText(_translate("WindowNomenklatura", "НАЗАД"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    WindowNomenklatura = QtWidgets.QMainWindow()
    ui = Ui_WindowNomenklatura()
    ui.setupUi(WindowNomenklatura)
    WindowNomenklatura.show()
    sys.exit(app.exec())
