# Form implementation generated from reading ui file 'production.ui'
#
# Created by: PyQt6 UI code generator 6.3.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_WindowProduction(object):
    def setupUi(self, WindowProduction):
        WindowProduction.setObjectName("WindowProduction")
        WindowProduction.resize(370, 600)
        self.centralwidget = QtWidgets.QWidget(WindowProduction)
        self.centralwidget.setMinimumSize(QtCore.QSize(370, 600))
        self.centralwidget.setMaximumSize(QtCore.QSize(370, 600))
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_title = QtWidgets.QLabel(self.centralwidget)
        self.label_title.setMaximumSize(QtCore.QSize(16777215, 60))
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(20)
        self.label_title.setFont(font)
        self.label_title.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.label_title.setScaledContents(True)
        self.label_title.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_title.setWordWrap(False)
        self.label_title.setObjectName("label_title")
        self.verticalLayout.addWidget(self.label_title)
        self.btn_nomenklatura = QtWidgets.QPushButton(self.centralwidget)
        self.btn_nomenklatura.setEnabled(True)
        self.btn_nomenklatura.setMinimumSize(QtCore.QSize(0, 65))
        self.btn_nomenklatura.setMaximumSize(QtCore.QSize(500, 65))
        self.btn_nomenklatura.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(22)
        font.setBold(False)
        self.btn_nomenklatura.setFont(font)
        self.btn_nomenklatura.setStyleSheet("QPushButton {\n"
"background-color: rgb(228, 107, 134);\n"
"border: none;\n"
"border-radius: 10px}\n"
"\n"
"QPushButton:hover {\n"
"border: 1px solid  rgb(0, 0, 0);\n"
"background-color: rgba(228, 107, 134, 0.9)\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"border:3px solid  rgb(0, 0, 0);\n"
"background-color: rgba(228, 107, 134, 1)\n"
"}")
        self.btn_nomenklatura.setCheckable(False)
        self.btn_nomenklatura.setObjectName("btn_nomenklatura")
        self.verticalLayout.addWidget(self.btn_nomenklatura)
        self.btn_tp = QtWidgets.QPushButton(self.centralwidget)
        self.btn_tp.setEnabled(True)
        self.btn_tp.setMinimumSize(QtCore.QSize(0, 65))
        self.btn_tp.setMaximumSize(QtCore.QSize(500, 65))
        self.btn_tp.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(22)
        font.setBold(False)
        self.btn_tp.setFont(font)
        self.btn_tp.setStyleSheet("QPushButton {\n"
"background-color: rgb(228, 107, 134);\n"
"border: none;\n"
"border-radius: 10px}\n"
"\n"
"QPushButton:hover {\n"
"border: 1px solid  rgb(0, 0, 0);\n"
"background-color: rgba(228, 107, 134, 0.9)\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"border:3px solid  rgb(0, 0, 0);\n"
"background-color: rgba(228, 107, 134, 1)\n"
"}")
        self.btn_tp.setCheckable(False)
        self.btn_tp.setObjectName("btn_tp")
        self.verticalLayout.addWidget(self.btn_tp)
        self.btn_1 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_1.setEnabled(True)
        self.btn_1.setMinimumSize(QtCore.QSize(0, 65))
        self.btn_1.setMaximumSize(QtCore.QSize(500, 65))
        self.btn_1.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(22)
        font.setBold(False)
        self.btn_1.setFont(font)
        self.btn_1.setStyleSheet("QPushButton {\n"
"background-color: rgb(228, 107, 134);\n"
"border: none;\n"
"border-radius: 10px}\n"
"\n"
"QPushButton:hover {\n"
"border: 1px solid  rgb(0, 0, 0);\n"
"background-color: rgba(228, 107, 134, 0.9)\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"border:3px solid  rgb(0, 0, 0);\n"
"background-color: rgba(228, 107, 134, 1)\n"
"}")
        self.btn_1.setCheckable(False)
        self.btn_1.setObjectName("btn_1")
        self.verticalLayout.addWidget(self.btn_1)
        self.btn_2 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_2.setEnabled(True)
        self.btn_2.setMinimumSize(QtCore.QSize(0, 65))
        self.btn_2.setMaximumSize(QtCore.QSize(500, 65))
        self.btn_2.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(22)
        font.setBold(False)
        self.btn_2.setFont(font)
        self.btn_2.setStyleSheet("QPushButton {\n"
"background-color: rgb(228, 107, 134);\n"
"border: none;\n"
"border-radius: 10px}\n"
"\n"
"QPushButton:hover {\n"
"border: 1px solid  rgb(0, 0, 0);\n"
"background-color: rgba(228, 107, 134, 0.9)\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"border:3px solid  rgb(0, 0, 0);\n"
"background-color: rgba(228, 107, 134, 1)\n"
"}")
        self.btn_2.setCheckable(False)
        self.btn_2.setObjectName("btn_2")
        self.verticalLayout.addWidget(self.btn_2)
        self.btn_3 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_3.setEnabled(True)
        self.btn_3.setMinimumSize(QtCore.QSize(0, 65))
        self.btn_3.setMaximumSize(QtCore.QSize(500, 65))
        self.btn_3.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(22)
        font.setBold(False)
        self.btn_3.setFont(font)
        self.btn_3.setStyleSheet("QPushButton {\n"
"background-color: rgb(228, 107, 134);\n"
"border: none;\n"
"border-radius: 10px}\n"
"\n"
"QPushButton:hover {\n"
"border: 1px solid  rgb(0, 0, 0);\n"
"background-color: rgba(228, 107, 134, 0.9)\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"border:3px solid  rgb(0, 0, 0);\n"
"background-color: rgba(228, 107, 134, 1)\n"
"}")
        self.btn_3.setCheckable(False)
        self.btn_3.setObjectName("btn_3")
        self.verticalLayout.addWidget(self.btn_3)
        self.btn_back = QtWidgets.QPushButton(self.centralwidget)
        self.btn_back.setEnabled(True)
        self.btn_back.setMinimumSize(QtCore.QSize(0, 65))
        self.btn_back.setMaximumSize(QtCore.QSize(500, 65))
        self.btn_back.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(22)
        font.setBold(False)
        self.btn_back.setFont(font)
        self.btn_back.setStyleSheet("QPushButton {\n"
"background-color: rgb(228, 107, 134);\n"
"border: none;\n"
"border-radius: 10px}\n"
"\n"
"QPushButton:hover {\n"
"border: 1px solid  rgb(0, 0, 0);\n"
"background-color: rgba(228, 107, 134, 0.9)\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"border:3px solid  rgb(0, 0, 0);\n"
"background-color: rgba(228, 107, 134, 1)\n"
"}")
        self.btn_back.setCheckable(False)
        self.btn_back.setObjectName("btn_back")
        self.verticalLayout.addWidget(self.btn_back)
        WindowProduction.setCentralWidget(self.centralwidget)

        self.retranslateUi(WindowProduction)
        QtCore.QMetaObject.connectSlotsByName(WindowProduction)

    def retranslateUi(self, WindowProduction):
        _translate = QtCore.QCoreApplication.translate
        WindowProduction.setWindowTitle(_translate("WindowProduction", "Выберите раздел"))
        self.label_title.setText(_translate("WindowProduction", "Выберите раздел"))
        self.btn_nomenklatura.setText(_translate("WindowProduction", "НОМЕНКЛАТУРА"))
        self.btn_tp.setText(_translate("WindowProduction", "ТЕХ. ПРОЦЕССЫ"))
        self.btn_1.setText(_translate("WindowProduction", "В РАЗРАБОТКЕ"))
        self.btn_2.setText(_translate("WindowProduction", "В РАЗРАБОТКЕ"))
        self.btn_3.setText(_translate("WindowProduction", "В РАЗРАБОТКЕ"))
        self.btn_back.setText(_translate("WindowProduction", "НАЗАД"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    WindowProduction = QtWidgets.QMainWindow()
    ui = Ui_WindowProduction()
    ui.setupUi(WindowProduction)
    WindowProduction.show()
    sys.exit(app.exec())
