# Form implementation generated from reading ui file 'prognoz_table.ui'
#
# Created by: PyQt6 UI code generator 6.3.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_prognoz_table(object):
    def setupUi(self, prognoz_table):
        prognoz_table.setObjectName("prognoz_table")
        prognoz_table.resize(1203, 811)
        self.centralwidget = QtWidgets.QWidget(prognoz_table)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.verticalLayout.addWidget(self.tableWidget)
        prognoz_table.setCentralWidget(self.centralwidget)

        self.retranslateUi(prognoz_table)
        QtCore.QMetaObject.connectSlotsByName(prognoz_table)

    def retranslateUi(self, prognoz_table):
        _translate = QtCore.QCoreApplication.translate
        prognoz_table.setWindowTitle(_translate("prognoz_table", "Работа с коэффициентами"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    prognoz_table = QtWidgets.QMainWindow()
    ui = Ui_prognoz_table()
    ui.setupUi(prognoz_table)
    prognoz_table.show()
    sys.exit(app.exec())
