# Form implementation generated from reading ui file 'sections.ui'
#
# Created by: PyQt6 UI code generator 6.3.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_WindowSections(object):
    def setupUi(self, WindowSections):
        WindowSections.setObjectName("WindowSections")
        WindowSections.resize(370, 600)
        WindowSections.setMinimumSize(QtCore.QSize(370, 600))
        WindowSections.setMaximumSize(QtCore.QSize(370, 600))
        self.centralwidget = QtWidgets.QWidget(WindowSections)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_title = QtWidgets.QLabel(self.centralwidget)
        self.label_title.setMaximumSize(QtCore.QSize(16777215, 60))
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(20)
        self.label_title.setFont(font)
        self.label_title.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.label_title.setScaledContents(True)
        self.label_title.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_title.setWordWrap(False)
        self.label_title.setObjectName("label_title")
        self.verticalLayout.addWidget(self.label_title)
        self.btn_logistics = QtWidgets.QPushButton(self.centralwidget)
        self.btn_logistics.setEnabled(False)
        self.btn_logistics.setMinimumSize(QtCore.QSize(0, 65))
        self.btn_logistics.setMaximumSize(QtCore.QSize(500, 65))
        self.btn_logistics.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(22)
        font.setBold(False)
        font.setWeight(50)
        self.btn_logistics.setFont(font)
        self.btn_logistics.setStyleSheet("QPushButton {\n"
"background-color: rgb(228, 107, 134);\n"
"border: none;\n"
"border-radius: 10px}\n"
"\n"
"QPushButton:hover {\n"
"border: 1px solid  rgb(0, 0, 0);\n"
"background-color: rgba(228, 107, 134, 0.9)\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"border:3px solid  rgb(0, 0, 0);\n"
"background-color: rgba(228, 107, 134, 1)\n"
"}")
        self.btn_logistics.setCheckable(False)
        self.btn_logistics.setObjectName("btn_logistics")
        self.verticalLayout.addWidget(self.btn_logistics)
        self.btn_trade = QtWidgets.QPushButton(self.centralwidget)
        self.btn_trade.setEnabled(False)
        self.btn_trade.setMinimumSize(QtCore.QSize(0, 65))
        self.btn_trade.setMaximumSize(QtCore.QSize(500, 65))
        self.btn_trade.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(22)
        font.setBold(False)
        font.setWeight(50)
        self.btn_trade.setFont(font)
        self.btn_trade.setStyleSheet("QPushButton {\n"
"background-color: rgb(228, 107, 134);\n"
"border: none;\n"
"border-radius: 10px}\n"
"\n"
"QPushButton:hover {\n"
"border: 1px solid  rgb(0, 0, 0);\n"
"background-color: rgba(228, 107, 134, 0.9)\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"border:3px solid  rgb(0, 0, 0);\n"
"background-color: rgba(228, 107, 134, 1)\n"
"}")
        self.btn_trade.setCheckable(False)
        self.btn_trade.setObjectName("btn_trade")
        self.verticalLayout.addWidget(self.btn_trade)
        self.btn_production = QtWidgets.QPushButton(self.centralwidget)
        self.btn_production.setEnabled(False)
        self.btn_production.setMinimumSize(QtCore.QSize(0, 65))
        self.btn_production.setMaximumSize(QtCore.QSize(500, 65))
        self.btn_production.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(22)
        font.setBold(False)
        font.setWeight(50)
        self.btn_production.setFont(font)
        self.btn_production.setStyleSheet("QPushButton {\n"
"background-color: rgb(228, 107, 134);\n"
"border: none;\n"
"border-radius: 10px}\n"
"\n"
"QPushButton:hover {\n"
"border: 1px solid  rgb(0, 0, 0);\n"
"background-color: rgba(228, 107, 134, 0.9)\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"border:3px solid  rgb(0, 0, 0);\n"
"background-color: rgba(228, 107, 134, 1)\n"
"}")
        self.btn_production.setCheckable(False)
        self.btn_production.setObjectName("btn_production")
        self.verticalLayout.addWidget(self.btn_production)
        self.btn_office = QtWidgets.QPushButton(self.centralwidget)
        self.btn_office.setEnabled(False)
        self.btn_office.setMinimumSize(QtCore.QSize(0, 65))
        self.btn_office.setMaximumSize(QtCore.QSize(500, 65))
        self.btn_office.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(22)
        font.setBold(False)
        font.setWeight(50)
        self.btn_office.setFont(font)
        self.btn_office.setStyleSheet("QPushButton {\n"
"background-color: rgb(228, 107, 134);\n"
"border: none;\n"
"border-radius: 10px}\n"
"\n"
"QPushButton:hover {\n"
"border: 1px solid  rgb(0, 0, 0);\n"
"background-color: rgba(228, 107, 134, 0.9)\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"border:3px solid  rgb(0, 0, 0);\n"
"background-color: rgba(228, 107, 134, 1)\n"
"}")
        self.btn_office.setCheckable(False)
        self.btn_office.setObjectName("btn_office")
        self.verticalLayout.addWidget(self.btn_office)
        self.btn_control = QtWidgets.QPushButton(self.centralwidget)
        self.btn_control.setEnabled(False)
        self.btn_control.setMinimumSize(QtCore.QSize(0, 65))
        self.btn_control.setMaximumSize(QtCore.QSize(500, 65))
        self.btn_control.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(22)
        font.setBold(False)
        font.setWeight(50)
        self.btn_control.setFont(font)
        self.btn_control.setStyleSheet("QPushButton {\n"
"background-color: rgb(228, 107, 134);\n"
"border: none;\n"
"border-radius: 10px}\n"
"\n"
"QPushButton:hover {\n"
"border: 1px solid  rgb(0, 0, 0);\n"
"background-color: rgba(228, 107, 134, 0.9)\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"border:3px solid  rgb(0, 0, 0);\n"
"background-color: rgba(228, 107, 134, 1)\n"
"}")
        self.btn_control.setCheckable(False)
        self.btn_control.setObjectName("btn_control")
        self.verticalLayout.addWidget(self.btn_control)
        self.btn_exit = QtWidgets.QPushButton(self.centralwidget)
        self.btn_exit.setMinimumSize(QtCore.QSize(0, 65))
        self.btn_exit.setMaximumSize(QtCore.QSize(500, 65))
        self.btn_exit.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(22)
        font.setBold(False)
        font.setWeight(50)
        self.btn_exit.setFont(font)
        self.btn_exit.setStyleSheet("QPushButton {\n"
"background-color: rgb(228, 107, 134);\n"
"border: none;\n"
"border-radius: 10px}\n"
"\n"
"QPushButton:hover {\n"
"border: 1px solid  rgb(0, 0, 0);\n"
"background-color: rgba(228, 107, 134, 0.9)\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"border:3px solid  rgb(0, 0, 0);\n"
"background-color: rgba(228, 107, 134, 1)\n"
"}")
        self.btn_exit.setCheckable(False)
        self.btn_exit.setObjectName("btn_exit")
        self.verticalLayout.addWidget(self.btn_exit)
        WindowSections.setCentralWidget(self.centralwidget)

        self.retranslateUi(WindowSections)
        QtCore.QMetaObject.connectSlotsByName(WindowSections)

    def retranslateUi(self, WindowSections):
        _translate = QtCore.QCoreApplication.translate
        WindowSections.setWindowTitle(_translate("WindowSections", "Выбор раздела"))
        self.label_title.setText(_translate("WindowSections", "Выберите раздел"))
        self.btn_logistics.setText(_translate("WindowSections", "ЛОГИСТИКА"))
        self.btn_trade.setText(_translate("WindowSections", "ТОРГОВЛЯ"))
        self.btn_production.setText(_translate("WindowSections", "ПРОИЗВОДСТВО"))
        self.btn_office.setText(_translate("WindowSections", "ОФИС"))
        self.btn_control.setText(_translate("WindowSections", "УПРАВЛЕНИЕ"))
        self.btn_exit.setText(_translate("WindowSections", "ВЫХОД"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    WindowSections = QtWidgets.QMainWindow()
    ui = Ui_WindowSections()
    ui.setupUi(WindowSections)
    WindowSections.show()
    sys.exit(app.exec())
