# Form implementation generated from reading ui file 'autoOrders.ui'
#
# Created by: PyQt6 UI code generator 6.3.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_WindowAutoOrders(object):
    def setupUi(self, WindowAutoOrders):
        WindowAutoOrders.setObjectName("WindowAutoOrders")
        WindowAutoOrders.resize(370, 600)
        self.centralwidget = QtWidgets.QWidget(WindowAutoOrders)
        self.centralwidget.setMinimumSize(QtCore.QSize(370, 600))
        self.centralwidget.setMaximumSize(QtCore.QSize(370, 600))
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_title = QtWidgets.QLabel(self.centralwidget)
        self.label_title.setMaximumSize(QtCore.QSize(16777215, 60))
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(20)
        self.label_title.setFont(font)
        self.label_title.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.label_title.setScaledContents(True)
        self.label_title.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_title.setWordWrap(False)
        self.label_title.setObjectName("label_title")
        self.verticalLayout.addWidget(self.label_title)
        self.btn_bakery = QtWidgets.QPushButton(self.centralwidget)
        self.btn_bakery.setEnabled(True)
        self.btn_bakery.setMinimumSize(QtCore.QSize(0, 65))
        self.btn_bakery.setMaximumSize(QtCore.QSize(500, 65))
        self.btn_bakery.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(22)
        font.setBold(False)
        font.setWeight(50)
        self.btn_bakery.setFont(font)
        self.btn_bakery.setStyleSheet("QPushButton {\n"
"background-color: rgb(228, 107, 134);\n"
"border: none;\n"
"border-radius: 10px}\n"
"\n"
"QPushButton:hover {\n"
"border: 1px solid  rgb(0, 0, 0);\n"
"background-color: rgba(228, 107, 134, 0.9)\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"border:3px solid  rgb(0, 0, 0);\n"
"background-color: rgba(228, 107, 134, 1)\n"
"}")
        self.btn_bakery.setCheckable(False)
        self.btn_bakery.setObjectName("btn_bakery")
        self.verticalLayout.addWidget(self.btn_bakery)
        self.btn_pie = QtWidgets.QPushButton(self.centralwidget)
        self.btn_pie.setEnabled(True)
        self.btn_pie.setMinimumSize(QtCore.QSize(0, 65))
        self.btn_pie.setMaximumSize(QtCore.QSize(500, 65))
        self.btn_pie.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(22)
        font.setBold(False)
        font.setWeight(50)
        self.btn_pie.setFont(font)
        self.btn_pie.setStyleSheet("QPushButton {\n"
"background-color: rgb(228, 107, 134);\n"
"border: none;\n"
"border-radius: 10px}\n"
"\n"
"QPushButton:hover {\n"
"border: 1px solid  rgb(0, 0, 0);\n"
"background-color: rgba(228, 107, 134, 0.9)\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"border:3px solid  rgb(0, 0, 0);\n"
"background-color: rgba(228, 107, 134, 1)\n"
"}")
        self.btn_pie.setCheckable(False)
        self.btn_pie.setObjectName("btn_pie")
        self.verticalLayout.addWidget(self.btn_pie)
        self.btn_cake = QtWidgets.QPushButton(self.centralwidget)
        self.btn_cake.setEnabled(True)
        self.btn_cake.setMinimumSize(QtCore.QSize(0, 65))
        self.btn_cake.setMaximumSize(QtCore.QSize(500, 65))
        self.btn_cake.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(22)
        font.setBold(False)
        font.setWeight(50)
        self.btn_cake.setFont(font)
        self.btn_cake.setStyleSheet("QPushButton {\n"
"background-color: rgb(228, 107, 134);\n"
"border: none;\n"
"border-radius: 10px}\n"
"\n"
"QPushButton:hover {\n"
"border: 1px solid  rgb(0, 0, 0);\n"
"background-color: rgba(228, 107, 134, 0.9)\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"border:3px solid  rgb(0, 0, 0);\n"
"background-color: rgba(228, 107, 134, 1)\n"
"}")
        self.btn_cake.setCheckable(False)
        self.btn_cake.setObjectName("btn_cake")
        self.verticalLayout.addWidget(self.btn_cake)
        self.btn_filling = QtWidgets.QPushButton(self.centralwidget)
        self.btn_filling.setEnabled(True)
        self.btn_filling.setMinimumSize(QtCore.QSize(0, 65))
        self.btn_filling.setMaximumSize(QtCore.QSize(500, 65))
        self.btn_filling.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(22)
        font.setBold(False)
        font.setWeight(50)
        self.btn_filling.setFont(font)
        self.btn_filling.setStyleSheet("QPushButton {\n"
"background-color: rgb(228, 107, 134);\n"
"border: none;\n"
"border-radius: 10px}\n"
"\n"
"QPushButton:hover {\n"
"border: 1px solid  rgb(0, 0, 0);\n"
"background-color: rgba(228, 107, 134, 0.9)\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"border:3px solid  rgb(0, 0, 0);\n"
"background-color: rgba(228, 107, 134, 1)\n"
"}")
        self.btn_filling.setCheckable(False)
        self.btn_filling.setObjectName("btn_filling")
        self.verticalLayout.addWidget(self.btn_filling)
        self.btn_pass = QtWidgets.QPushButton(self.centralwidget)
        self.btn_pass.setEnabled(True)
        self.btn_pass.setMinimumSize(QtCore.QSize(0, 65))
        self.btn_pass.setMaximumSize(QtCore.QSize(500, 65))
        self.btn_pass.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(22)
        font.setBold(False)
        font.setWeight(50)
        self.btn_pass.setFont(font)
        self.btn_pass.setStyleSheet("QPushButton {\n"
"background-color: rgb(228, 107, 134);\n"
"border: none;\n"
"border-radius: 10px}\n"
"\n"
"QPushButton:hover {\n"
"border: 1px solid  rgb(0, 0, 0);\n"
"background-color: rgba(228, 107, 134, 0.9)\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"border:3px solid  rgb(0, 0, 0);\n"
"background-color: rgba(228, 107, 134, 1)\n"
"}")
        self.btn_pass.setCheckable(False)
        self.btn_pass.setObjectName("btn_pass")
        self.verticalLayout.addWidget(self.btn_pass)
        self.btn_back = QtWidgets.QPushButton(self.centralwidget)
        self.btn_back.setEnabled(True)
        self.btn_back.setMinimumSize(QtCore.QSize(0, 65))
        self.btn_back.setMaximumSize(QtCore.QSize(500, 65))
        self.btn_back.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(22)
        font.setBold(False)
        font.setWeight(50)
        self.btn_back.setFont(font)
        self.btn_back.setStyleSheet("QPushButton {\n"
"background-color: rgb(228, 107, 134);\n"
"border: none;\n"
"border-radius: 10px}\n"
"\n"
"QPushButton:hover {\n"
"border: 1px solid  rgb(0, 0, 0);\n"
"background-color: rgba(228, 107, 134, 0.9)\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"border:3px solid  rgb(0, 0, 0);\n"
"background-color: rgba(228, 107, 134, 1)\n"
"}")
        self.btn_back.setCheckable(False)
        self.btn_back.setObjectName("btn_back")
        self.verticalLayout.addWidget(self.btn_back)
        WindowAutoOrders.setCentralWidget(self.centralwidget)

        self.retranslateUi(WindowAutoOrders)
        QtCore.QMetaObject.connectSlotsByName(WindowAutoOrders)

    def retranslateUi(self, WindowAutoOrders):
        _translate = QtCore.QCoreApplication.translate
        WindowAutoOrders.setWindowTitle(_translate("WindowAutoOrders", "Выберите раздел"))
        self.label_title.setText(_translate("WindowAutoOrders", "Выберите раздел"))
        self.btn_bakery.setText(_translate("WindowAutoOrders", "ВЫПЕЧКА"))
        self.btn_pie.setText(_translate("WindowAutoOrders", "ПИРОЖНЫЕ"))
        self.btn_cake.setText(_translate("WindowAutoOrders", "ТОРТЫ"))
        self.btn_filling.setText(_translate("WindowAutoOrders", "НАЧИНКИ"))
        self.btn_pass.setText(_translate("WindowAutoOrders", "В РАЗРАБОТКЕ"))
        self.btn_back.setText(_translate("WindowAutoOrders", "НАЗАД"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    WindowAutoOrders = QtWidgets.QMainWindow()
    ui = Ui_WindowAutoOrders()
    ui.setupUi(WindowAutoOrders)
    WindowAutoOrders.show()
    sys.exit(app.exec())
