# Form implementation generated from reading ui file 'control.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_WindowControl(object):
    def setupUi(self, WindowControl):
        WindowControl.setObjectName("WindowControl")
        WindowControl.resize(370, 600)
        WindowControl.setMinimumSize(QtCore.QSize(370, 600))
        WindowControl.setMaximumSize(QtCore.QSize(370, 600))
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(14)
        WindowControl.setFont(font)
        WindowControl.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.ArrowCursor))
        WindowControl.setMouseTracking(False)
        WindowControl.setTabletTracking(False)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("images/icon.ico"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        WindowControl.setWindowIcon(icon)
        WindowControl.setStyleSheet("background: #fff")
        self.centralwidget = QtWidgets.QWidget(parent=WindowControl)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_section = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_section.setMinimumSize(QtCore.QSize(0, 60))
        self.label_section.setMaximumSize(QtCore.QSize(16777215, 60))
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(20)
        self.label_section.setFont(font)
        self.label_section.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_section.setObjectName("label_section")
        self.verticalLayout.addWidget(self.label_section)
        self.btn_control_users = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_control_users.setMinimumSize(QtCore.QSize(0, 65))
        self.btn_control_users.setMaximumSize(QtCore.QSize(16777215, 65))
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(17)
        font.setBold(False)
        font.setWeight(50)
        self.btn_control_users.setFont(font)
        self.btn_control_users.setFocusPolicy(QtCore.Qt.FocusPolicy.StrongFocus)
        self.btn_control_users.setStyleSheet("QPushButton {\n"
"background-color: rgb(228, 107, 134);\n"
"border: none;\n"
"border-radius: 10px}\n"
"\n"
"QPushButton:hover {\n"
"border: 1px solid  rgb(0, 0, 0);\n"
"background-color: rgba(228, 107, 134, 0.9)\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"border:3px solid  rgb(0, 0, 0);\n"
"background-color: rgba(228, 107, 134, 1)\n"
"}")
        self.btn_control_users.setCheckable(False)
        self.btn_control_users.setObjectName("btn_control_users")
        self.verticalLayout.addWidget(self.btn_control_users)
        self.btn_config_DB = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_config_DB.setMinimumSize(QtCore.QSize(0, 65))
        self.btn_config_DB.setMaximumSize(QtCore.QSize(16777215, 65))
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(17)
        font.setBold(False)
        font.setWeight(50)
        self.btn_config_DB.setFont(font)
        self.btn_config_DB.setFocusPolicy(QtCore.Qt.FocusPolicy.StrongFocus)
        self.btn_config_DB.setStyleSheet("QPushButton {\n"
"background-color: rgb(228, 107, 134);\n"
"border: none;\n"
"border-radius: 10px}\n"
"\n"
"QPushButton:hover {\n"
"border: 1px solid  rgb(0, 0, 0);\n"
"background-color: rgba(228, 107, 134, 0.9)\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"border:3px solid  rgb(0, 0, 0);\n"
"background-color: rgba(228, 107, 134, 1)\n"
"}")
        self.btn_config_DB.setCheckable(False)
        self.btn_config_DB.setObjectName("btn_config_DB")
        self.verticalLayout.addWidget(self.btn_config_DB)
        self.btn_SQL_queries = QtWidgets.QPushButton(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(65)
        sizePolicy.setHeightForWidth(self.btn_SQL_queries.sizePolicy().hasHeightForWidth())
        self.btn_SQL_queries.setSizePolicy(sizePolicy)
        self.btn_SQL_queries.setMinimumSize(QtCore.QSize(0, 65))
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.btn_SQL_queries.setFont(font)
        self.btn_SQL_queries.setFocusPolicy(QtCore.Qt.FocusPolicy.StrongFocus)
        self.btn_SQL_queries.setStyleSheet("QPushButton {\n"
"background-color: rgb(228, 107, 134);\n"
"border: none;\n"
"border-radius: 10px}\n"
"\n"
"QPushButton:hover {\n"
"border: 1px solid  rgb(0, 0, 0);\n"
"background-color: rgba(228, 107, 134, 0.9)\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"border:3px solid  rgb(0, 0, 0);\n"
"background-color: rgba(228, 107, 134, 1)\n"
"}")
        self.btn_SQL_queries.setCheckable(False)
        self.btn_SQL_queries.setObjectName("btn_SQL_queries")
        self.verticalLayout.addWidget(self.btn_SQL_queries)
        self.btn_logs_editing = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_logs_editing.setMinimumSize(QtCore.QSize(0, 65))
        self.btn_logs_editing.setMaximumSize(QtCore.QSize(16777215, 65))
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(17)
        font.setBold(False)
        font.setWeight(50)
        self.btn_logs_editing.setFont(font)
        self.btn_logs_editing.setFocusPolicy(QtCore.Qt.FocusPolicy.StrongFocus)
        self.btn_logs_editing.setStyleSheet("QPushButton {\n"
"background-color: rgb(228, 107, 134);\n"
"border: none;\n"
"border-radius: 10px}\n"
"\n"
"QPushButton:hover {\n"
"border: 1px solid  rgb(0, 0, 0);\n"
"background-color: rgba(228, 107, 134, 0.9)\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"border:3px solid  rgb(0, 0, 0);\n"
"background-color: rgba(228, 107, 134, 1)\n"
"}")
        self.btn_logs_editing.setCheckable(False)
        self.btn_logs_editing.setObjectName("btn_logs_editing")
        self.verticalLayout.addWidget(self.btn_logs_editing)
        self.btn_release_updates = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_release_updates.setMinimumSize(QtCore.QSize(0, 65))
        self.btn_release_updates.setMaximumSize(QtCore.QSize(16777215, 65))
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(17)
        font.setBold(False)
        font.setWeight(50)
        self.btn_release_updates.setFont(font)
        self.btn_release_updates.setFocusPolicy(QtCore.Qt.FocusPolicy.StrongFocus)
        self.btn_release_updates.setStyleSheet("QPushButton {\n"
"background-color: rgb(228, 107, 134);\n"
"border: none;\n"
"border-radius: 10px}\n"
"\n"
"QPushButton:hover {\n"
"border: 1px solid  rgb(0, 0, 0);\n"
"background-color: rgba(228, 107, 134, 0.9)\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"border:3px solid  rgb(0, 0, 0);\n"
"background-color: rgba(228, 107, 134, 1)\n"
"}")
        self.btn_release_updates.setCheckable(False)
        self.btn_release_updates.setObjectName("btn_release_updates")
        self.verticalLayout.addWidget(self.btn_release_updates)
        self.btn_back = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_back.setMinimumSize(QtCore.QSize(0, 65))
        self.btn_back.setMaximumSize(QtCore.QSize(16777215, 65))
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(17)
        font.setBold(False)
        font.setWeight(50)
        self.btn_back.setFont(font)
        self.btn_back.setFocusPolicy(QtCore.Qt.FocusPolicy.StrongFocus)
        self.btn_back.setStyleSheet("QPushButton {\n"
"background-color: rgb(228, 107, 134);\n"
"border: none;\n"
"border-radius: 10px}\n"
"\n"
"QPushButton:hover {\n"
"border: 1px solid  rgb(0, 0, 0);\n"
"background-color: rgba(228, 107, 134, 0.9)\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"border:3px solid  rgb(0, 0, 0);\n"
"background-color: rgba(228, 107, 134, 1)\n"
"}")
        self.btn_back.setCheckable(False)
        self.btn_back.setObjectName("btn_back")
        self.verticalLayout.addWidget(self.btn_back)
        WindowControl.setCentralWidget(self.centralwidget)

        self.retranslateUi(WindowControl)
        QtCore.QMetaObject.connectSlotsByName(WindowControl)

    def retranslateUi(self, WindowControl):
        _translate = QtCore.QCoreApplication.translate
        WindowControl.setWindowTitle(_translate("WindowControl", "Малина 64"))
        self.label_section.setText(_translate("WindowControl", "Панель управления"))
        self.btn_control_users.setText(_translate("WindowControl", "Управление пользователями"))
        self.btn_control_users.setShortcut(_translate("WindowControl", "Return"))
        self.btn_config_DB.setText(_translate("WindowControl", "Настройки подключения к БД"))
        self.btn_config_DB.setShortcut(_translate("WindowControl", "Return"))
        self.btn_SQL_queries.setText(_translate("WindowControl", "Получение других данных из БД"))
        self.btn_SQL_queries.setShortcut(_translate("WindowControl", "Return"))
        self.btn_logs_editing.setText(_translate("WindowControl", "Редактирование логов"))
        self.btn_logs_editing.setShortcut(_translate("WindowControl", "Return"))
        self.btn_release_updates.setText(_translate("WindowControl", "Выпуск обновлений"))
        self.btn_release_updates.setShortcut(_translate("WindowControl", "Return"))
        self.btn_back.setText(_translate("WindowControl", "К ВЫБОРУ РАЗДЕЛА"))
        self.btn_back.setShortcut(_translate("WindowControl", "Return"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    WindowControl = QtWidgets.QMainWindow()
    ui = Ui_WindowControl()
    ui.setupUi(WindowControl)
    WindowControl.show()
    sys.exit(app.exec())
