# Form implementation generated from reading ui file 'sections.ui'
#
# Created by: PyQt6 UI code generator 6.3.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_WindowSections(object):
    def setupUi(self, WindowSections):
        WindowSections.setObjectName("WindowSections")
        WindowSections.resize(370, 600)
        WindowSections.setMinimumSize(QtCore.QSize(370, 600))
        WindowSections.setMaximumSize(QtCore.QSize(370, 600))
        self.centralwidget = QtWidgets.QWidget(WindowSections)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_title = QtWidgets.QLabel(self.centralwidget)
        self.label_title.setMaximumSize(QtCore.QSize(16777215, 60))
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(20)
        self.label_title.setFont(font)
        self.label_title.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.label_title.setScaledContents(True)
        self.label_title.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_title.setWordWrap(False)
        self.label_title.setObjectName("label_title")
        self.verticalLayout.addWidget(self.label_title)
        self.btn_autoorders = QtWidgets.QPushButton(self.centralwidget)
        self.btn_autoorders.setEnabled(False)
        self.btn_autoorders.setMinimumSize(QtCore.QSize(0, 65))
        self.btn_autoorders.setMaximumSize(QtCore.QSize(500, 65))
        self.btn_autoorders.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(22)
        font.setBold(False)
        font.setWeight(50)
        self.btn_autoorders.setFont(font)
        self.btn_autoorders.setStyleSheet("QPushButton {\n"
"background-color: rgb(228, 107, 134);\n"
"border: none;\n"
"border-radius: 10px}\n"
"\n"
"QPushButton:hover {\n"
"border: 1px solid  rgb(0, 0, 0);\n"
"background-color: rgba(228, 107, 134, 0.9)\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"border:3px solid  rgb(0, 0, 0);\n"
"background-color: rgba(228, 107, 134, 1)\n"
"}")
        self.btn_autoorders.setCheckable(False)
        self.btn_autoorders.setObjectName("btn_autoorders")
        self.verticalLayout.addWidget(self.btn_autoorders)
        self.btn_wage = QtWidgets.QPushButton(self.centralwidget)
        self.btn_wage.setEnabled(False)
        self.btn_wage.setMinimumSize(QtCore.QSize(0, 65))
        self.btn_wage.setMaximumSize(QtCore.QSize(500, 65))
        self.btn_wage.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(22)
        font.setBold(False)
        font.setWeight(50)
        self.btn_wage.setFont(font)
        self.btn_wage.setStyleSheet("QPushButton {\n"
"background-color: rgb(228, 107, 134);\n"
"border: none;\n"
"border-radius: 10px}\n"
"\n"
"QPushButton:hover {\n"
"border: 1px solid  rgb(0, 0, 0);\n"
"background-color: rgba(228, 107, 134, 0.9)\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"border:3px solid  rgb(0, 0, 0);\n"
"background-color: rgba(228, 107, 134, 1)\n"
"}")
        self.btn_wage.setCheckable(False)
        self.btn_wage.setObjectName("btn_wage")
        self.verticalLayout.addWidget(self.btn_wage)
        self.btn_comingsoon = QtWidgets.QPushButton(self.centralwidget)
        self.btn_comingsoon.setEnabled(False)
        self.btn_comingsoon.setMinimumSize(QtCore.QSize(0, 65))
        self.btn_comingsoon.setMaximumSize(QtCore.QSize(500, 65))
        self.btn_comingsoon.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(22)
        font.setBold(False)
        font.setWeight(50)
        self.btn_comingsoon.setFont(font)
        self.btn_comingsoon.setStyleSheet("QPushButton {\n"
"background-color: rgb(228, 107, 134);\n"
"border: none;\n"
"border-radius: 10px}\n"
"\n"
"QPushButton:hover {\n"
"border: 1px solid  rgb(0, 0, 0);\n"
"background-color: rgba(228, 107, 134, 0.9)\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"border:3px solid  rgb(0, 0, 0);\n"
"background-color: rgba(228, 107, 134, 1)\n"
"}")
        self.btn_comingsoon.setCheckable(False)
        self.btn_comingsoon.setObjectName("btn_comingsoon")
        self.verticalLayout.addWidget(self.btn_comingsoon)
        self.btn_history = QtWidgets.QPushButton(self.centralwidget)
        self.btn_history.setEnabled(False)
        self.btn_history.setMinimumSize(QtCore.QSize(0, 65))
        self.btn_history.setMaximumSize(QtCore.QSize(500, 65))
        self.btn_history.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(22)
        font.setBold(False)
        font.setWeight(50)
        self.btn_history.setFont(font)
        self.btn_history.setStyleSheet("QPushButton {\n"
"background-color: rgb(228, 107, 134);\n"
"border: none;\n"
"border-radius: 10px}\n"
"\n"
"QPushButton:hover {\n"
"border: 1px solid  rgb(0, 0, 0);\n"
"background-color: rgba(228, 107, 134, 0.9)\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"border:3px solid  rgb(0, 0, 0);\n"
"background-color: rgba(228, 107, 134, 1)\n"
"}")
        self.btn_history.setCheckable(False)
        self.btn_history.setObjectName("btn_history")
        self.verticalLayout.addWidget(self.btn_history)
        self.btn_control = QtWidgets.QPushButton(self.centralwidget)
        self.btn_control.setEnabled(False)
        self.btn_control.setMinimumSize(QtCore.QSize(0, 65))
        self.btn_control.setMaximumSize(QtCore.QSize(500, 65))
        self.btn_control.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(22)
        font.setBold(False)
        font.setWeight(50)
        self.btn_control.setFont(font)
        self.btn_control.setStyleSheet("QPushButton {\n"
"background-color: rgb(228, 107, 134);\n"
"border: none;\n"
"border-radius: 10px}\n"
"\n"
"QPushButton:hover {\n"
"border: 1px solid  rgb(0, 0, 0);\n"
"background-color: rgba(228, 107, 134, 0.9)\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"border:3px solid  rgb(0, 0, 0);\n"
"background-color: rgba(228, 107, 134, 1)\n"
"}")
        self.btn_control.setCheckable(False)
        self.btn_control.setObjectName("btn_control")
        self.verticalLayout.addWidget(self.btn_control)
        self.btn_exit = QtWidgets.QPushButton(self.centralwidget)
        self.btn_exit.setMinimumSize(QtCore.QSize(0, 65))
        self.btn_exit.setMaximumSize(QtCore.QSize(500, 65))
        self.btn_exit.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(22)
        font.setBold(False)
        font.setWeight(50)
        self.btn_exit.setFont(font)
        self.btn_exit.setStyleSheet("QPushButton {\n"
"background-color: rgb(228, 107, 134);\n"
"border: none;\n"
"border-radius: 10px}\n"
"\n"
"QPushButton:hover {\n"
"border: 1px solid  rgb(0, 0, 0);\n"
"background-color: rgba(228, 107, 134, 0.9)\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"border:3px solid  rgb(0, 0, 0);\n"
"background-color: rgba(228, 107, 134, 1)\n"
"}")
        self.btn_exit.setCheckable(False)
        self.btn_exit.setObjectName("btn_exit")
        self.verticalLayout.addWidget(self.btn_exit)
        WindowSections.setCentralWidget(self.centralwidget)

        self.retranslateUi(WindowSections)
        QtCore.QMetaObject.connectSlotsByName(WindowSections)

    def retranslateUi(self, WindowSections):
        _translate = QtCore.QCoreApplication.translate
        WindowSections.setWindowTitle(_translate("WindowSections", "Выбор раздела"))
        self.label_title.setText(_translate("WindowSections", "Выберите раздел"))
        self.btn_autoorders.setText(_translate("WindowSections", "АВТОЗАКАЗЫ"))
        self.btn_wage.setText(_translate("WindowSections", "ЗАРПЛАТА"))
        self.btn_comingsoon.setText(_translate("WindowSections", "В РАЗРАБОТКЕ"))
        self.btn_history.setText(_translate("WindowSections", "ИСТОРИЯ"))
        self.btn_control.setText(_translate("WindowSections", "УПРАВЛЕНИЕ"))
        self.btn_exit.setText(_translate("WindowSections", "ВЫХОД"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    WindowSections = QtWidgets.QMainWindow()
    ui = Ui_WindowSections()
    ui.setupUi(WindowSections)
    WindowSections.show()
    sys.exit(app.exec())
