# Form implementation generated from reading ui file 'usersControl.ui'
#
# Created by: PyQt6 UI code generator 6.3.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_WindowUserControl(object):
    def setupUi(self, WindowUserControl):
        WindowUserControl.setObjectName("WindowUserControl")
        WindowUserControl.resize(1280, 720)
        WindowUserControl.setMinimumSize(QtCore.QSize(1280, 720))
        WindowUserControl.setMaximumSize(QtCore.QSize(1280, 720))
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(14)
        WindowUserControl.setFont(font)
        WindowUserControl.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.ArrowCursor))
        WindowUserControl.setMouseTracking(False)
        WindowUserControl.setTabletTracking(False)
        WindowUserControl.setStyleSheet("background: #fff")
        self.centralwidget = QtWidgets.QWidget(WindowUserControl)
        self.centralwidget.setObjectName("centralwidget")
        self.btn_back = QtWidgets.QPushButton(self.centralwidget)
        self.btn_back.setGeometry(QtCore.QRect(1020, 10, 231, 51))
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.btn_back.setFont(font)
        self.btn_back.setFocusPolicy(QtCore.Qt.FocusPolicy.StrongFocus)
        self.btn_back.setStyleSheet("QPushButton {\n"
"background-color: rgb(228, 107, 134);\n"
"border: none;\n"
"border-radius: 10px}\n"
"\n"
"QPushButton:hover {\n"
"border: 1px solid  rgb(0, 0, 0);\n"
"background-color: rgba(228, 107, 134, 0.9)\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"border:3px solid  rgb(0, 0, 0);\n"
"background-color: rgba(228, 107, 134, 1)\n"
"}")
        self.btn_back.setCheckable(False)
        self.btn_back.setObjectName("btn_back")
        self.label_windowName = QtWidgets.QLabel(self.centralwidget)
        self.label_windowName.setGeometry(QtCore.QRect(10, 10, 981, 51))
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(26)
        self.label_windowName.setFont(font)
        self.label_windowName.setAlignment(QtCore.Qt.AlignmentFlag.AlignHCenter|QtCore.Qt.AlignmentFlag.AlignTop)
        self.label_windowName.setObjectName("label_windowName")
        WindowUserControl.setCentralWidget(self.centralwidget)

        self.retranslateUi(WindowUserControl)
        QtCore.QMetaObject.connectSlotsByName(WindowUserControl)

    def retranslateUi(self, WindowUserControl):
        _translate = QtCore.QCoreApplication.translate
        WindowUserControl.setWindowTitle(_translate("WindowUserControl", "Управление пользователями"))
        self.btn_back.setText(_translate("WindowUserControl", "НАЗАД"))
        self.btn_back.setShortcut(_translate("WindowUserControl", "Return"))
        self.label_windowName.setText(_translate("WindowUserControl", "Панель управления пользователями"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    WindowUserControl = QtWidgets.QMainWindow()
    ui = Ui_WindowUserControl()
    ui.setupUi(WindowUserControl)
    WindowUserControl.show()
    sys.exit(app.exec())
